### ISSUE TITLE
lad 情况

### ISSUE THREAD

**Issue by sunbeyond40** [Kayryu/shell-faucet#1]
请问lad还有在开发维护吗？ 目前一个交易所可以交易的买，最近项目方可以宣传上，争取重新上交易所（抹茶或hotbit），跟上波卡热度。

**Comment by sunbeyond40** [comment]
请问lad还有在开发维护吗？ 目前没有一个交易所可以交易，最近项目方可以宣传上，争取重新上交易所（抹茶或hotbit），跟上波卡热度。

**Comment by Kayryu** [comment]
目前没有在维护项目。

sam <notifications@github.com> 于2020年8月11日周二 上午11:08写道：

**Comment by Kayryu** [comment]
> 请问lad还有在开发维护吗？ 目前没有一个交易所可以交易，最近项目方可以宣传上，争取重新上交易所（抹茶或hotbit），跟上波卡热度。

感谢对Lad项目的支持，目前只有少量开发维护。

**Comment by sunbeyond40** [comment]
没有更新代码也行，我是觉得，重新上所就好
